geonetwork:
  core:
    url: http://localhost:8080/geonetwork
  index:
    url: http://localhost:9200
    indexPrefix: gn-
    indexRecordName: gn-records
  openapi:
    url: http://localhost:7979

server:
  port: 7979

spring:
  application:
    name: GeoNetwork
  datasource:
    url: jdbc:h2:mem:gn5
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  cloud:
    gateway:
      mvc:
        routes:
          - id: geonetwork_proxy_redirect
            uri: ${geonetwork.openapi.url}
            predicates:
              - Path=/geonetwork/proxy
            filters:
              - RewritePath=/geonetwork/(?<url>.*), /api/$\{url}
          - id: geonetwork_route
            uri: ${geonetwork.core.url}
            predicates:
              - Path=/geonetwork/**
management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /doc/api/


debug: false
