/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodeListValue } from './codeListValue';

export interface AttributeTable {
  name?: string;
  definition?: string;
  code?: string;
  link?: string;
  type?: string;
  cardinality?: string;
  values?: Array<CodeListValue>;
}
