/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The spatial extent of the features in the collection.
 */
export interface ExtentSpatial {
  /**
   * One or more bounding boxes that describe the spatial extent of the dataset. In the Core only a single bounding box is supported.  Extensions may support additional areas. The first bounding box describes the overall spatial extent of the data. All subsequent bounding boxes describe more precise bounding boxes, e.g., to identify clusters of data. Clients only interested in the overall spatial extent will only need to access the first bounding box in the array.
   */
  bbox?: Array<Array<number>>;
  /**
   * Coordinate reference system of the coordinates in the spatial extent (property `bbox`). The default reference system is WGS 84 longitude/latitude. In the Core the only other supported coordinate reference system is WGS 84 longitude/latitude/ellipsoidal height for coordinates with height. Extensions may support additional coordinate reference systems and add additional enum values.
   */
  crs?: ExtentSpatial.CrsEnum;
}
export namespace ExtentSpatial {
  export const CrsEnum = {
    HttpWwwOpengisNetDefCrsOgc13Crs84: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
    HttpWwwOpengisNetDefCrsOgc0Crs84h: 'http://www.opengis.net/def/crs/OGC/0/CRS84h',
  } as const;
  export type CrsEnum = (typeof CrsEnum)[keyof typeof CrsEnum];
}
