/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The temporal extent of the features in the collection.
 */
export interface ExtentTemporal {
  /**
   * One or more time intervals that describe the temporal extent of the dataset. In the Core only a single time interval is supported.  Extensions may support multiple intervals. The first time interval describes the overall temporal extent of the data. All subsequent time intervals describe more precise time intervals, e.g., to identify clusters of data. Clients only interested in the overall temporal extent will only need to access the first time interval in the array (a pair of lower and upper bound instants).
   */
  interval?: Array<Array<string>>;
  /**
   * Coordinate reference system of the coordinates in the temporal extent (property `interval`). The default reference system is the Gregorian calendar. In the Core this is the only supported temporal coordinate reference system. Extensions may support additional temporal coordinate reference systems and add additional enum values.
   */
  trs?: ExtentTemporal.TrsEnum;
}
export namespace ExtentTemporal {
  export const TrsEnum = {
    HttpWwwOpengisNetDefUomIso86010Gregorian: 'http://www.opengis.net/def/uom/ISO-8601/0/Gregorian',
  } as const;
  export type TrsEnum = (typeof TrsEnum)[keyof typeof TrsEnum];
}
