/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeTable } from './attributeTable';

export interface FeatureType {
  typeName?: string;
  definition?: string;
  code?: string;
  isAbstract?: string;
  aliases?: Array<string>;
  attributeTable?: Array<AttributeTable>;
}
