/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileInfo } from './profileInfo';

export interface FormatterInfo {
  mimeType?: string;
  schemas?: Set<string>;
  profile?: ProfileInfo;
}
