/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Link {
  protocol?: string;
  function?: string;
  applicationProfile?: string;
  group?: string;
  mimeType?: string;
  nilReason?: string;
  hash?: string;
  idx?: string;
  urlObject?: { [key: string]: string };
  nameObject?: { [key: string]: string };
  descriptionObject?: { [key: string]: string };
}
