/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetadataResourceExternalManagementProperties } from './metadataResourceExternalManagementProperties';

export interface MetadataResource {
  visibility?: MetadataResource.VisibilityEnum;
  id?: string;
  size?: number;
  version?: string;
  url?: string;
  filename?: string;
  metadataUuid?: string;
  metadataResourceExternalManagementProperties?: MetadataResourceExternalManagementProperties;
  lastModification?: string;
  approved?: boolean;
  metadataId?: number;
}
export namespace MetadataResource {
  export const VisibilityEnum = {
    Public: 'public',
    Private: 'private',
  } as const;
  export type VisibilityEnum = (typeof VisibilityEnum)[keyof typeof VisibilityEnum];
}
