/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OgcApiRecordsFacetResultBucketDto } from './ogcApiRecordsFacetResultBucketDto';


export interface OgcApiRecordsFacetSummaryDto { 
    type?: string;
    property?: string;
    buckets?: Array<OgcApiRecordsFacetResultBucketDto>;
    more?: boolean;
}

