/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OgcApiRecordsLinkTemplateDto } from './ogcApiRecordsLinkTemplateDto';
import { OgcApiRecordsCatalogDto } from './ogcApiRecordsCatalogDto';
import { OgcApiRecordsLinkDto } from './ogcApiRecordsLinkDto';


export interface OgcApiRecordsLandingPageDto { 
    title?: string;
    description?: string;
    catalogInfo?: OgcApiRecordsCatalogDto;
    links?: Array<OgcApiRecordsLinkDto>;
    linkTemplates?: Array<OgcApiRecordsLinkTemplateDto>;
}

