/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OgcApiRecordsFacetHistogramDto } from './ogcApiRecordsFacetHistogramDto';
import { OgcApiRecordsFacetFilterDto } from './ogcApiRecordsFacetFilterDto';
import { OgcApiRecordsFacetTermsDto } from './ogcApiRecordsFacetTermsDto';


/**
 * @type OgcApiRecordsFacetsDtoFacetsValue
 * @export
 */
export type OgcApiRecordsFacetsDtoFacetsValue = OgcApiRecordsFacetFilterDto | OgcApiRecordsFacetHistogramDto | OgcApiRecordsFacetTermsDto;

