/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OgcApiRecordsFacetDto } from './ogcApiRecordsFacetDto';

export interface OgcApiRecordsFacetTermsDto extends OgcApiRecordsFacetDto {
  /**
   * Name of the property
   */
  property?: string;
  'x-elastic-property'?: string;
  bucketCount?: number;
  sortedBy?: OgcApiRecordsFacetTermsDto.SortedByEnum;
  minOccurs?: number;
}
export namespace OgcApiRecordsFacetTermsDto {
  export const SortedByEnum = {
    Count: 'count',
    Value: 'value',
  } as const;
  export type SortedByEnum = (typeof SortedByEnum)[keyof typeof SortedByEnum];
}
