/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Telephone numbers at which contact can be made.
 */
export interface OgcApiRecordsPhoneDto { 
    /**
     * The value is the phone number itself.
     */
    value: string;
    /**
     * The type of phone number (e.g. home, work, fax, etc.).
     */
    roles?: Array<string>;
}

