/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Email addresses at which contact can be made.
 */
export interface OgcApiRecordsEmailDto { 
    /**
     * The value is the email number itself.
     */
    value: string;
    /**
     * The type of email (e.g. home, work, etc.).
     */
    roles?: Array<string>;
}

