/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OgcApiRecordsFacetsDtoFacetsValue } from './ogcApiRecordsFacetsDtoFacetsValue';


export interface OgcApiRecordsFacetsDto { 
    id: string;
    title?: string;
    defaultBucketCount?: number;
    facets?: { [key: string]: OgcApiRecordsFacetsDtoFacetsValue; };
}

