/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A list of schemes used in this context.
 */
export interface OgcApiRecordsSchemeDto { 
    /**
     * An identifier for this namespace.  The identifier can be used as a short-form for the namespace.
     */
    'scheme-id': string;
    /**
     * A declarative region that provides a scope to the identifiers inside it. It is recommended that the value of namespace be a URI.
     */
    namespace: string;
    /**
     * An extensible description of a mechanism that resolves a scheme identifier (scheme-id) to its namespace.
     */
    resolver?: object;
}

