/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OgcApiRecordsGnElasticDto } from './ogcApiRecordsGnElasticDto';
import { OgcApiRecordsJsonItemDto } from './ogcApiRecordsJsonItemDto';

export interface OgcApiRecordsJsonPropertyDto {
  title?: string;
  type?: string;
  description?: string;
  format?: string;
  enumeration?: Array<string>;
  item?: OgcApiRecordsJsonItemDto;
  'x-ogc-role'?: string;
  'x-gn-elastic'?: Array<OgcApiRecordsGnElasticDto>;
}
