/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecordLink { 
    type?: string;
    origin?: RecordLink.OriginEnum;
    to?: string;
    title?: string;
    url?: string;
    associationType?: string;
    initiativeType?: string;
}
export namespace RecordLink {
    export const OriginEnum = {
        Remote: 'remote',
        Catalog: 'catalog'
    } as const;
    export type OriginEnum = typeof OriginEnum[keyof typeof OriginEnum];
}


