/**
 * GeoNetwork 4.4.9 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SiteInformation { 
    catalogue?: { [key: string]: string; };
    database?: { [key: string]: string; };
    env?: { [key: string]: string; };
    index?: { [key: string]: string; };
    main?: { [key: string]: string; };
    version?: { [key: string]: string; };
}

