geonetwork:
  openapi-records:
    ogcapi-records-json:
      includeRawXML: false
      includeElasticJson: false
    links:
      base-path: /ogcapi-records
      # Where is GN5's ogcapi-records located?
      # should end in "/" and shouldn't have "//" in the path
      ogcApiRecordsBaseUrl: ${GN5_BASE_URL:http:////localhost:7979/}${geonetwork.openapi-records.links.base-path}/
      # How to link to GN (can be either GN4 or GN5's GN4 proxy)
      # should end in "/" and shouldn't have "//" in the path
      gnBaseUrl: ${GN4_PROXY_BASE_URL:http:////localhost:7979/geonetwork}/

      # These define what kinds of links should be shown for the ogcapi-records various documents.
      # You probably will not need to modify these.
      landingpage:
        formats:
          - json
          - html
      conformance:
        formats:
          - json
          - html
      collections:
        formats:
          - json
          - html
      collection:
        formats:
          - json
          - html
      queryables:
        formats:
          - json
      items:
        formats:
          - geojson
          - json
      item:
        #formats taken from the formatter api
        # this defines the default profile for a mime type
        profileDefaults:
          - mimetype: application/geo+json
            defaultProfile: http://www.opengis.net/def/profile/OGC/0/ogc-record
          - mimetype: application/json
            defaultProfile: http://www.opengis.net/def/profile/OGC/0/ogc-record
          - mimetype: application/rdf+xml
            defaultProfile: http://geonetwork.net/def/profile/dcat
          - mimetype: application/xml
            defaultProfile: http://geonetwork.net/def/profile/raw-xml
    search:
      # This query filter is always added to all queries
      queryFilter: '+isTemplate:n'
      # When executing a normal `q=...` query, this defines how we do an elastic search.
      queryBase: '(any.\*:(${any}) OR resourceTitleObject.\*:(${any})^2)'
      # Should the elastic query track total hits?  Tracking total hits is expensive, however, is needed for paging.
      trackTotalHits: true
      # What elastic index json record sources (properties) should be retrieved during a query?
      sources:
        - "*"
