geonetwork:
  4:
    url: ${GN4_BASE_URL:http://localhost:8080/geonetwork}
    path: >
      /srv,
      /static/,
      /images/,
      /catalog/,
      /map/,
      /criticalhealthcheck,
      /warninghealthcheck,
      /jolokia,
      /xml/,
      /index/,
      /doc/api/index.html,
      /doc/api/swagger-ui.css,
      /doc/api/swagger-ui-bundle.js,
      /doc/api/swagger-ui-standalone-preset.js
